CREATE DATABASE IF NOT EXISTS dbPedido;
USE dbPedido;

CREATE TABLE articulo (
	ARTICULO_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRECIO FLOAT NOT NULL,
	PRIMARY KEY  (`ARTICULO_ID`)
);

CREATE TABLE cliente (
	CLIENTE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	RAZON_SOCIAL VARCHAR(50)  NOT NULL,
	RUC VARCHAR(11)  NOT NULL,
	TELEFONO VARCHAR(20)  NOT NULL,
	DIRECCION VARCHAR(50)  NOT NULL,
	REPRESENTANTE VARCHAR(50)  NOT NULL,
	DNI VARCHAR(11)  NOT NULL,
	PRIMARY KEY  (`CLIENTE_ID`)
);

CREATE TABLE pedido (
	PEDIDO_ID BIGINT(20) NOT NULL auto_increment,
	CLIENTE_ID BIGINT(20) NOT NULL,
	FECHA_PEDIDO date NOT NULL,
	PRIMARY KEY  (`PEDIDO_ID`),
	KEY `CLIENTE_PEDIDO` (`CLIENTE_ID`),
	CONSTRAINT `CLIENTE_PEDIDO` FOREIGN KEY (`CLIENTE_ID`) REFERENCES `cliente` (`CLIENTE_ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pedido_item (
	PEDIDO_ITEM_ID BIGINT(20) NOT NULL auto_increment,
	PEDIDO_ID BIGINT(20) NOT NULL,
	CANTIDAD float NOT NULL,
	ARTICULO_ID BIGINT(20) NOT NULL,
	PRECIO float NOT NULL,
	PRIMARY KEY  (`PEDIDO_ITEM_ID`),
	KEY `ARTICULO_ITEM` (`ARTICULO_ID`),
	CONSTRAINT `PEDIDO_ITEM` FOREIGN KEY (`PEDIDO_ID`) REFERENCES `pedido` (`PEDIDO_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT `ARTICULO_ITEM` FOREIGN KEY (`ARTICULO_ID`) REFERENCES `articulo` (`ARTICULO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
);